import type { Metadata } from "next";
import "../globals.css";
import Menu from "@/components/Menu";
// import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "|| Vem Ser Mesch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Menu page={'social'} />
      {children}
      {/* <Footer /> */}
    </>
  );
}
