import type { Metadata } from "next";
import "./globals.css";
// import Menu from "@/components/Menu";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "|| Grupo Mensch",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon_gm.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {/* <Menu page={''}/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
