import type { Metadata } from "next";
import "../globals.css";
import Head from "next/head";
// import Menu from "@/components/Menu";
// import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "|| Mensch Energia Solar",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon_es.ico",
    
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <link rel="icon" href="./favicon.ico" type="image/x-icon" sizes="32x32" />
      </Head>
      {/* <Menu page={'about'} /> */}
      {children}
      {/* <Footer /> */}
    </>
  );
}
